name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Docker image
        run: docker build -f Master/Linux/Dockerfile -t drod --output . .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: drod-tss-5.2-x86_64.AppImage
